name: lawgen
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # --- CORE DEPENDENCIES ---
  http: ^1.1.0 
  webview_flutter: ^4.2.2
  webview_flutter_web: ^0.2.2
  shared_preferences: ^2.2.0
  uuid: ^4.1.0
  intl: ^0.18.1 # <-- Constrained for compatibility
  get_it: ^7.6.4
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # --- CONSTRAINED FOR COMPATIBILITY ---
  flutter_lints: ^2.0.0 # Using an older major version for maximum compatibility
  mockito: ^5.4.0      # Constrained for compatibility

# --- THIS IS THE MOST IMPORTANT PART ---
# This FORCES mockito to a specific version, no matter what other packages want.
dependency_overrides:
  mockito: 5.4.4
  flutter_lints: 2.0.3